version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: [ "nodemon", "index.js" ]
    depends_on:
      - postgres
  postgres:
    image: postgres:16.0-alpine
    ports:
      - '5433:5432'
    # this persists data between runs
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  database-data: {}
  node_modules: {}
